<?php

namespace PrestaShop\PrestaShop\Core\Payment;

/**
 * We define 4 types of payment options:.
 *
 * - the "offline" kind: simple URL to call + information to display (e.g. bankwire, cheque)
 * - the "external" kind: simple URL to call, but payment processed on PSP's website (e.g. simple paypal)
 * - the "embedded" kind: you write your credit card info in a form that is on your site and not inside an iframe (e.g. stripe)
 * - the "iframe" kind: payment form is displayed on your website but inside an iframe (e.g. atos)
 */
class PaymentOption implements \PrestaShopBundle\Service\Hook\HookContentClassInterface
{
    /**
     * Return Call to Action Text.
     *
     * @return string
     */
    public function getCallToActionText()
    {
    }
    /**
     * Set Call To Action Text.
     *
     * @param string $callToActionText
     *
     * @return $this
     */
    public function setCallToActionText($callToActionText)
    {
    }
    /**
     * Return Additional Information.
     *
     * @return string
     */
    public function getAdditionalInformation()
    {
    }
    /**
     * Set Additional Information.
     *
     * @param string $additionalInformation
     *
     * @return $this
     */
    public function setAdditionalInformation($additionalInformation)
    {
    }
    /**
     * Return logo path.
     *
     * @return string
     */
    public function getLogo()
    {
    }
    /**
     * Set logo path.
     *
     * @param string $logo
     *
     * @return $this
     */
    public function setLogo($logo)
    {
    }
    /**
     * Return action to perform (POST/GET).
     *
     * @return string
     */
    public function getAction()
    {
    }
    /**
     * Set action to be performed by this option.
     *
     * @param string $action
     *
     * @return $this
     */
    public function setAction($action)
    {
    }
    /**
     * Return inputs contained in this payment option.
     *
     * @return array
     */
    public function getInputs()
    {
    }
    /**
     * Set inputs for this payment option.
     *
     * @param array $inputs
     *
     * @return $this
     */
    public function setInputs($inputs)
    {
    }
    /**
     * Get payment option form.
     *
     * @return string
     */
    public function getForm()
    {
    }
    /**
     * Set payment option form.
     *
     * @param string|null $form
     *
     * @return $this
     */
    public function setForm($form)
    {
    }
    /**
     * Get related module name to this payment option.
     *
     * @return string
     */
    public function getModuleName()
    {
    }
    /**
     * Set related module name to this payment option.
     *
     * @param string $moduleName
     *
     * @return $this
     */
    public function setModuleName($moduleName)
    {
    }
    /**
     * Was the module form generated by
     * binaries ?
     *
     * @return bool
     */
    public function isBinary()
    {
    }
    /**
     * Set if the form was generated by binaries.
     *
     * @param bool $binary
     *
     * @return $this
     */
    public function setBinary($binary)
    {
    }
    public function toArray()
    {
    }
    /**
     * Legacy options were specified this way:
     * - either an array with a top level property 'cta_text' and then the other properties
     * - or a numerically indexed array or arrays as described above.
     *
     * Since this was a mess, this method is provided to convert them.
     * It takes as input a legacy option (in either form) and always
     * returns an array of instances of PrestaShop\PrestaShop\Core\Payment\PaymentOption
     */
    public static function convertLegacyOption(array $legacyOption)
    {
    }
}
