<?php

namespace PrestaShop\PrestaShop\Adapter\Container;

/**
 * This interface is only used when we build containers for legacy environment. It
 * is common to LegacyContainer and LegacyContainerBuilder.
 *
 * It allows to easily (and without losing performance) detect if the container is a
 * Symfony one (generated by kernel) or a legacy one (generated by PrestaShop core).
 */
interface LegacyContainerInterface extends \Symfony\Component\DependencyInjection\ContainerInterface
{
}
