<?php

namespace PrestaShopBundle\Entity\Repository;

/**
 * AttributeGroupRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Finds attribute groups by language and shop.
     *
     * @param int $idLang Language ID
     * @param int $idShop Shop ID
     *
     * @return \PrestaShopBundle\Entity\AttributeGroup[]
     */
    public function findByLangAndShop(int $idLang, int $idShop): array
    {
    }
    /**
     * Finds attribute groups by language and shops.
     *
     * @param int $idLang Language ID
     * @param int[] $idShops Shop IDs
     *
     * @return \PrestaShopBundle\Entity\AttributeGroup[]
     */
    public function findByLangForShops(int $idLang, array $idShops): array
    {
    }
}
