<?php

namespace PrestaShopBundle\Entity\Repository;

/**
 * TabLangRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabLangRepository extends \Doctrine\ORM\EntityRepository
{
}
